import { db } from "@/db";
import { jobPostings } from "@/db/schema";

const data = [
  {
    _id: "66569c734465d3cca810bf1c",
    jobTitle: "Floor Covering Installer",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "GL Installations Inc.",
    addressLocality: "Burnaby",
    addressRegion: "BC",
    language: "English",
    minCompValue: "30",
    compTimeUnit: "HOUR",
    email: "info@glinstallations.ca",
    jobPageId: "floor-covering-installer-19",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<div>\n\tTerms of Employment:&nbsp;</div>\n<div>\n\tPermanent, Full Time</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tSalary:</div>\n<div>\n\t$30.00 Hourly, for 30.00 Hours per week</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tAvailable positions:&nbsp;</div>\n<div>\n\t1</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tAnticipated Start Date:&nbsp;</div>\n<div>\n\tAs soon as possible</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tLocation:</div>\n<div>\n\tSeveral location in Lower Mainland, BC and main office 1512 Maplehurst Circle, Burnaby, BC V5A 2V6</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tEducation:</div>\n<div>\n\tNo formal education required</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tExperience:</div>\n<div>\n\tMinimum 2 years of experience required</div>\n<div>\n\tLanguages:</div>\n<div>\n\tWritten and Spoken English is required</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tDuties:</div>\n<div>\n\t• Inspect, measure and mark surfaces to be covered</div>\n<div>\n\t• Measure, cut and fasten underlay and underpadding</div>\n<div>\n\t• Measure, cut and install carpeting using hand or machine stitcher, seaming iron, bonding tape or other bonding materials</div>\n<div>\n\t• Stretch carpeting using knee-kicker or power stretcher and secure carpeting to floor or other surfaces using staple gun or other devices</div>\n<div>\n\t• Measure, cut and install resilient floor covering using adhesive, rollers and other hand tools</div>\n<div>\n\t• Install hardwood floors, such as strip floors, block floors or plank floors, using glue, staples, nails or other means</div>\n<div>\n\t• Inspect and repair damaged floor coverings</div>\n<div>\n\t• May estimate material and labour costs.</div>\n<div>\n\t• May supervise records management technicians and related staff.</div>\n<div>\n\tWork Conditions and Physical Capabilities: Physically demanding</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tEssential Skills:</div>\n<div>\n\tOral communication, Working with others, Problem solving, Decision making, Job task planning and organizing</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tEmployer:</div>\n<div>\n\tGL Installations Inc.</div>\n<div>\n\t1512 Maplehurst Circle, Burnaby, BC. V5A 2V6</div>\n<div>\n\t&nbsp;</div>\n<div>\n\t&nbsp;</div>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c734465d3cca810bf1e",
    jobTitle: "Office administrative assistant",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Apollo Homes Ltd",
    addressLocality: "Winnipeg",
    addressRegion: "MB",
    language: "English",
    minCompValue: "24",
    compTimeUnit: "HOUR",
    email: "jagbir@apollohomes.ca",
    jobPageId: "office-administrative-assistant-312",
    employmentSubType: "Full Time",
    validThrough: "2024-11-23T08:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<address><span style="font-size: 14px;"><span style="font-family: arial,helvetica,sans-serif;">Permanent employment, Full time</span></span></address>\n<address><span style="font-size: 14px;"><span style="font-family: arial,helvetica,sans-serif;">35 to 40 hours per Week</span></span></address>\n<address><span style="font-size: 14px;"><span style="font-family: arial,helvetica,sans-serif;">No of Vacancies-1</span></span></address>\n<address><span style="font-size: 14px;"><span style="font-family: arial,helvetica,sans-serif;">Salary : $24 Hourly</span></span></address>\n<h3 style="font-family: Roboto, Helvetica, Arial, sans-serif; line-height: 1.1; margin: 30px 0px 0px; font-size: 20px;">Responsibilities</h3>\n<h4 style="font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.1; margin: 20px 0px 8px; font-size: 16px;">Tasks</h4>\n<ul class="csvlist" style="margin: 5px 0px; padding-right: 0px; padding-left: 0px; list-style-type: none; font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 15px;">\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Open and distribute mail and other materials</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Schedule and confirm appointments</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Answer telephone and relay telephone calls and messages</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Answer electronic enquiries</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Compile data, statistics and other information</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Order office supplies and maintain inventory</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Greet people and direct them to contacts or service areas</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Set up and maintain manual and computerized information filing systems</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Perform data entry</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Provide customer service</li>\n<li style="line-height: normal; margin: 0px 0px 5px 20px;">Maintain and manage digital database</li>\n</ul>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf20",
    jobTitle: "Administrative Secretary",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Pioneer Thinking Consulting Corporation",
    addressLocality: "Richmond",
    addressRegion: "BC",
    language: "English",
    minCompValue: "25",
    compTimeUnit: "HOUR",
    email: "PTCCYVR@GMAIL.COM",
    jobPageId: "administrative-secretary-4",
    employmentSubType: "Full Time",
    validThrough: "2024-11-23T08:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tTitle: Administrative Secretary</p>\n<p>\n\tSalary: 25.00$/hour</p>\n<p>\n\tEmployment Type: Permanent full time (30 hours per week)</p>\n<p>\n\tVacancy: 1 Position available</p>\n<p>\n\tEmployment groups: Students, Youth, Veterans of the Canadian Armed Forces, Visible minorities, Persons with disabilities, Indigenous people, Newcomers to Canada, Seniors, Asylum seekers with valid work permits</p>\n<p>\n\tLanguage: English</p>\n<p>\n\tMinimum Education: High School, Post-secondary education in related field an asset</p>\n<p>\n\tExperience: at least 1 year experience in similar position</p>\n<p>\n\tNOC Group: 13110 – Administrative assistants</p>\n<p>\n\tJob Location: 1735 4311 Hazelbridge Way, Richmond, BC, V6X 3L7</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tJob Description:</p>\n<p>\n\tPioneer Thinking Consulting Corporation (PTCC) is hiring an administrative secretary based in Richmond head office. We provide marketing and management consulting services to our client. We need an administrative secretary to support our current team’s workload. As an administrative secretary, you will be responsible for the following tasks:</p>\n<p>\n\tPrepare, key in, edit and proofread correspondence, invoices, presentations, brochures, publications, reports and related material from machine dictation and handwritten copy, Open and distribute incoming regular and electronic mail and other material and coordinate the flow of information internally and with other departments and organizations, Schedule and confirm appointments and meetings of employer, Order office supplies and maintain inventory, Answer telephone and electronic enquiries and relay telephone calls and messages, Set up and maintain manual and computerized information filing systems, Determine and establish office procedures, Greet visitors, ascertain nature of business and direct visitors to employer or appropriate person, Record and prepare minutes of meetings, Arrange travel schedules and make reservations, compile data, statistics and other information to support research activities, Organize conferences. Arrange and co-ordinate seminars, conferences, etc. Coordinate the flow of information within the team, Record and prepare minutes of meetings, seminars and conferences, Schedule and confirm appointments, Manage contracts, Answer telephone and relay telephone calls and messages, Answer electronic enquiries, Compile data, statistics and other information, Order office supplies and maintain inventory, Arrange travel, related itineraries and make reservations, Greet people and direct them to contacts or service areas, Set up and maintain manual and computerized information filing systems, Work with the marketing department to understand and communicate marketing messages to the field, Maintain and manage digital database</p>\n<p>\n\tRequirements:&nbsp; Secondary school education, 1-2 years of similar position on fast paced working environment</p>\n<p>\n\tSalary is 25.00$ per hour for a Minimum of 30 hours per week.</p>\n<p>\n\tNote: The position will be working with teams across different time zones and stakeholders abroad; early morning, late afternoon to night and weekend working schedule is required.&nbsp; travel to other Canadian provinces such as Alberta, Saskatchewan, and Ontario on regular basis is required for up to 50% of the time.</p>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf22",
    jobTitle: "Food Service Supervisor",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "YUZU BOWL AND KITCHEN LTD. dba YUZU BOWL AND BISTRO",
    addressLocality: "Kelowna",
    addressRegion: "BC",
    language: "English",
    minCompValue: "18.00-$20.00",
    compTimeUnit: "HOUR",
    email: "YuzuBowl1573@hotmail.com",
    jobPageId: "food-service-supervisor-3257",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p align="center">\n\t<strong>Food Service Supervisor</strong></p>\n<p align="center">\n\t&nbsp;</p>\n<p align="left">\n\t<strong>YUZU BOWL AND KITCHEN LTD. dba YUZU BOWL AND BISTRO </strong>in Kelowna, BC is looking for a skilled, experienced Full-time, Permanent Food Service Supervisor.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong>Conditions:</strong></p>\n<ul>\n<li>\n\t\tPosition: Food Service Supervisor (NOC 62020)</li>\n<li>\n\t\tFull-Time, Permanent position</li>\n<li>\n\t\tWage: $18.00-$20.00 per hour (wage to be determined depending on experience and skills)</li>\n<li>\n\t\tWorking hours: 30-40 hours per week</li>\n<li>\n\t\tAbility to do shift work (daytime, evenings, weekends, and holidays)</li>\n<li>\n\t\tVacation: 10 days paid vacation per year or 4% gross salary</li>\n<li>\n\t\tBenefit: Free meals, Gratuities</li>\n<li>\n\t\tPositions Available: 1</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong>Requirements:</strong></p>\n<ul>\n<li>\n\t\tCompletion of secondary school</li>\n<li>\n\t\t2-3 years of experience in food preparation or service <strong><u>OR</u></strong> Completion of a community college program in food service administration, hotel and restaurant management, or related discipline is required</li>\n<li>\n\t\tLanguage: English</li>\n</ul>\n<p style="margin-left:36.0pt">\n\t&nbsp;</p>\n<p>\n\t<strong>Business Information:</strong></p>\n<ul>\n<li>\n\t\tWorking Location: 1573 Ellis St, Kelowna, BC V1Y 2A7</li>\n<li>\n\t\tBusiness Name: YUZU BOWL AND BISTRO</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong>Job Duties:</strong></p>\n<ul>\n<li>\n\t\tSupervise and coordinate activities of restaurant staff</li>\n<li>\n\t\tResolve customer complaints or concerns</li>\n<li>\n\t\tPrepare and manage work schedule</li>\n<li>\n\t\tMaintain records of stock, repairs, sales, and wastage</li>\n<li>\n\t\tEstimate and order supplies and ingredients</li>\n<li>\n\t\tEnsure that food and service meet quality control standards</li>\n<li>\n\t\tPerform cashier’s or server’s duties such as taking orders and processing payments if needs</li>\n</ul>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf24",
    jobTitle: "Kitchen Helpers",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Sushi on the Strip",
    addressLocality: "Cranbrook",
    addressRegion: "BC",
    language: "English",
    minCompValue: "17.40",
    compTimeUnit: "HOUR",
    email: "sushiots@outlook.com",
    jobPageId: "kitchen-helpers-78",
    employmentSubType: "Full Time",
    validThrough: "2024-11-23T08:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>Sushi on the Strip is located at C-1000 Cranbrook Street North, Cranbrook, BC V1C 3S3. We are currently looking for permanent, full time Kitchen Helpers. If you are interested, please submit your resume by e-mail.</p>\n<p>Position: Kitchen Helper<br>\nWage: CAD$17.40/hour<br>\nTypes: Full-time, Permanent (Part time also available)<br>\nWorking hours: 30~40 hours/week<br>\nBenefits: 4% of vacation pay, Free meals at work, Tips</p>\n<p>Job Duties:<br>\n• Wash and peel vegetables, fruit;<br>\n• Wash, clean, and sanitize work tables, meat blocks, appliances, cupboards and kitchen work areas;<br>\n• Sharpen kitchen knives;<br>\n• Handle and store cleaning products;<br>\n• Receive, unpack and store supplies in refrigerators, cupboards, and other storage areas;<br>\n• Sweep and mop floors, and perform other duties to assist cook and kitchen staff;<br>\n• Remove trash and clean kitchen garbage containers.</p>\n<p>Job Requirements:<br>\n• Education: not required;<br>\n• Experience: not required;<br>\n• On-the-job training provided.</p>\n<p>Language at work: English<br>\nJob Location: C-1000 Cranbrook Street North, Cranbrook, BC V1C 3S3</p>\n<p>Contact Information: Sushi on the Strip<br>\n• E-mail: sushiots@outlook.com</p>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf26",
    jobTitle: "Line Cooks (Japanese Foods)",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Gogo Sushi",
    addressLocality: "Lake Country",
    addressRegion: "BC",
    language: "English",
    minCompValue: "17.40",
    compTimeUnit: "HOUR",
    email: "turtlebaygogosushi@gmail.com",
    jobPageId: "line-cooks-japanese-foods-13",
    employmentSubType: "Full Time",
    validThrough: "2024-11-23T08:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>Gogo Sushi restaurant is located at 504-11850 Oceola Rd., Lake Country, BC, V4V 2T5. We are currently looking for permanent, full time Line Cooks (Japanese Foods). If you are interested, please submit your resume by e-mail.</p>\n<p>Position: Line Cook<br>\nWage: CAD$17.40/hour<br>\nWorking Hours: 30-40 hours/week<br>\nTerms of employment: Full-time, Permanent<br>\nBenefits: 4% of vacation pay, Free meals at work, Tips</p>\n<p>Job Duties:<br>\n• Prepare and cook various Japanese food items including donburi, teriyaki, tempura, udon, rolls, maki, etc, with rest of staff;<br>\n• Set up and stock stations with all necessary supplies;<br>\n• Maintain cleanliness and comply with food safety and sanitation requirements by properly handling food and ensuring correct storage;<br>\n• Clean and sanitize cooking surfaces at the end of the shift;<br>\n• Perform inventory checks and complete food storage logs.</p>\n<p>Job Requirements:<br>\n• Completion of secondary school;<br>\n• Completion of a three-year apprenticeship program for cooks or completion of college or other program in cooking or 1-2 years of commercial cooking experience.</p>\n<p>Language at work: English<br>\nWork Location: 504-11850 Oceola Rd., Lake Country, BC, V4V 2T5</p>\n<p>Contact Information: Gogo Sushi<br>\n• e-mail: turtlebaygogosushi@gmail.com</p>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf28",
    jobTitle: "Technical Support Analyst (NOC 22221)",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "13309291 Canada Inc.",
    addressLocality: "Brampton",
    addressRegion: "ON",
    language: "English",
    minCompValue: "29",
    compTimeUnit: "HOUR",
    email: "hr@skillmileconsulting.com",
    jobPageId: "technical-support-analyst-noc-22221-2",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tCompany Legal Name: 13309291 Canada Inc.</p>\n<p>\n\tCompany Operating Name: Skillmile Consulting</p>\n<p>\n\tBusiness Address: 1 Lisson Cres, Brampton, Ontario, L6X 5H8</p>\n<p>\n\tLocation of work: 1 Lisson Cres, Brampton, Ontario, L6X 5H8</p>\n<p>\n\tTitle of the position: Technical Support Analyst (NOC 22221)</p>\n<p>\n\tTerms of employment: Permanent position</p>\n<p>\n\tHours of work: 32-40 hours per week (full-time position)</p>\n<p>\n\tLanguage of work: English</p>\n<p>\n\tWage: $29 per hour</p>\n<p>\n\tContact information – email: &nbsp;<a href="mailto:hr@skillmileconsulting.com">hr@skillmileconsulting.com</a></p>\n<p>\n\tSkills requirements:</p>\n<ul>\n<li>\n\t\tEducation: Completion of any college diploma</li>\n<li>\n\t\tWork experience: At least 7 months to 1 year work experience as a Technical Support Analyst</li>\n</ul>\n<p>\n\tJob Duties:</p>\n<ul>\n<li>\n\t\tCommunicate electronically with computer application users experiencing difficulties to determine and document problems experienced</li>\n<li>\n\t\tConsult user guides, technical manuals and other documents to research and implement solutions</li>\n<li>\n\t\tReproduce, diagnose and resolve technical problems encountered by users</li>\n<li>\n\t\tProvide advice and training to users in response to identified difficulties</li>\n<li>\n\t\tProvide business systems support to users in response to identified difficulties</li>\n<li>\n\t\tCollect, organize and maintain a problems and solutions log for use by other technical support analysts and the development team</li>\n<li>\n\t\tParticipate in the redesign of applications and other software</li>\n<li>\n\t\tMay supervise other technical support workers in this group.</li>\n</ul>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf2a",
    jobTitle: "Ton Ton Sushi is seeking F/T First Cooks",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "1251769 BC Ltd dba Ton Ton Sushi",
    addressLocality: "Vancouver",
    addressRegion: "BC",
    language: "English",
    minCompValue: "29.00-$31.00",
    compTimeUnit: "HOUR",
    email: "tonton.broadway@outlook.com",
    jobPageId: "ton-ton-sushi-is-seeking-f-t-first-cooks",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\t<u>Position Info:</u></p>\n<ul>\n<li>\n\t\tPosition: First Cook</li>\n<li>\n\t\tTerms of employment: Full-time, Permanent</li>\n<li>\n\t\tWage: $29.00 ~ $31.00/hour (depending on experience)</li>\n<li>\n\t\tWorking Hours: 30~40 hours/week</li>\n<li>\n\t\tNumber of Positions:&nbsp; 2</li>\n<li>\n\t\tWork Location: 3667 West Broadway Street, Vancouver, BC V6R 2B8</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\t<u>Benefits:</u></p>\n<ul>\n<li>\n\t\t4% vacation pay</li>\n</ul>\n<p style="margin-left:36.0pt">\n\t&nbsp;</p>\n<p>\n\t<u>Job Duties:</u></p>\n<ul>\n<li>\n\t\tPrepare and cook entire meals and individual dishes and food items</li>\n<li>\n\t\tKeep track of food, supplies, and equipment inventory and records</li>\n<li>\n\t\tOrder kitchen supplies and equipment</li>\n<li>\n\t\tSupervise kitchen staff and helpers</li>\n<li>\n\t\tKeep the kitchen and work area clean and sanitized</li>\n<li>\n\t\tPlan menus, determine the sizes of food portions, and estimate food requirements and expenses</li>\n<li>\n\t\tRecruit and train other kitchen staff in the methods of food preparation, cooking, and handling of food</li>\n<li>\n\t\tOversee kitchen operation</li>\n</ul>\n<p style="margin-left:36.0pt">\n\t&nbsp;</p>\n<p>\n\t<u>Job requirements:</u></p>\n<ul>\n<li>\n\t\tLanguage: English</li>\n<li>\n\t\tEducation: Completion of Secondary School is required</li>\n<li>\n\t\tExperience: 2~3 years of commercial cooking experiences are required</li>\n</ul>\n<p style="margin-left:36.0pt">\n\t&nbsp;</p>\n<p>\n\t<u>How to Apply:</u></p>\n<ul>\n<li>\n\t\tCompany information: 1251769 BC Ltd dba Ton Ton Sushi</li>\n<li>\n\t\tEmail address: tonton.broadway@outlook.com</li>\n<li>\n\t\tPlease apply only via email</li>\n</ul>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf2c",
    jobTitle: "Graphic Designer (NOC 52120)",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Pixelpro204INC.",
    addressLocality: "Winnipeg",
    addressRegion: "MB",
    language: "English",
    minCompValue: "25.00",
    compTimeUnit: "HOUR",
    email: "pixelprojobs@outlook.com",
    jobPageId: "graphic-designer-noc-52120-3",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tPixelpro204INC. located at 67 Prairie Spring Bay, Winnipeg, Manitoba R2R 2Z6 is looking to hire a Graphic Designer (NOC 52120) as soon as possible.</p>\n<p>\n\t<br>\n\tSalary: $25.00/hour<br>\n\tPositions available: 01<br>\n\tJob type: Permanent, full time<br>\n\tLanguage: English</p>\n<p>\n\tJob Duties:</p>\n<ul>\n<li>\n\t\tEstimate time to complete graphic designs and illustrations</li>\n<li>\n\t\tConsult with clients to determine the nature and content of illustrations in order to meet their communications needs</li>\n<li>\n\t\tConsult with clients to establish the overall look, graphic elements and content of communications materials</li>\n<li>\n\t\tDevelop the graphic elements that meet the clients' objectives</li>\n<li>\n\t\tEstablish guidelines for illustrators or photographers</li>\n<li>\n\t\tPrepare sketches, layouts and graphic elements</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\tJob Requirements:<br>\n\t• College, CEGEP or other non-university certificate or diploma from a program of 3 months to less than 1 year is required.<br>\n\t• Experience 1 year to less than 2 years of relevant experience is required.</p>\n<p>\n\t&nbsp;</p>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf2e",
    jobTitle: "Cook",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Aera",
    addressLocality: "Toronto",
    addressRegion: "ON",
    language: "English",
    minCompValue: "16.55-22.00",
    compTimeUnit: "HOUR",
    email: "aerarecruitment@outlook.com",
    jobPageId: "cook-2651",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;vertical-align: baseline">We are looking for experienced </span><span style="font-size: 12pt;, serif;font-weight: 700;vertical-align: baseline">Cook</span><span style="font-size: 12pt;, serif;vertical-align: baseline">s for Aera, located at 8 Spadina Avenue, 38th Floor, Toronto, ON M5V 2H6, Canada. Cooks must have experience preparing food and dishes.</span></span></p>\n<p>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">No. of position: 6</span></span></p>\n<p>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">JOB DUTIES:</span></span></p>\n<ul dir="ltr">\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Follow all recipes and practice portion control to prepare, garnish, and present ordered items.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Prepare all sorts of appetizers and main courses as per the menu.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Accept special requests from patrons for menu items and prepare food.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Work as a team and prepare food orders within time limits.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Instruct kitchen assistants and helpers.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Maintain proper and adequate kitchen/station set-up daily. This includes requisitioning and stocking all required food, paper products, and condiments.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Handle, store, and rotate all products properly.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Responsible for set-up, regular maintenance, cleaning, and breakdown of machinery and equipment.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Responsible for maintaining stock, cutting, and storing all perishables daily to ensure product quality.</span></span></li>\n<li role="presentation" style="list-style-type: disc;font-size: 12pt;background-color: transparent;vertical-align: baseline;margin: 0pt -10.1pt 0pt -7.1pt;line-height: 1.2;text-align: justify">\n\t\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;background-color: transparent;vertical-align: baseline">Return all items used during your shift to the proper place, and clean and organize all work and storage areas.</span></span></li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">Prerequisites:</span></span></p>\n<p>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">Education: </span><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline"><span class="Apple-tab-span"> </span></span><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline"><span class="Apple-tab-span"> </span></span><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline"><span class="Apple-tab-span"> </span></span><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">No formal education is required&nbsp;</span></span></p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span style="text-indent: -144pt;background-color: transparent;font-size: 12pt;vertical-align: baseline">Experience &amp; Skills: </span><span style="text-indent: -144pt;background-color: transparent;font-size: 12pt;vertical-align: baseline"><span class="Apple-tab-span"> </span></span><span style="text-indent: -144pt;background-color: transparent;font-size: 12pt;vertical-align: baseline">1 year to less than 2 years of experience&nbsp;</span></p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span style="text-indent: -144pt;background-color: transparent;font-size: 12pt;vertical-align: baseline">Language:</span><span style="text-indent: -144pt;background-color: transparent;font-size: 12pt;vertical-align: baseline"><span class="Apple-tab-span"> </span></span><span style="text-indent: -144pt;background-color: transparent;font-size: 12pt;vertical-align: baseline">English</span></p>\n<p>\n\t<br>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">Hourly Rate: $ 16.55 to $ 22.00 per Hour for 30 to 40 Hours per week</span></span></p>\n<p>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">Starting Date: As soon as possible</span></span></p>\n<p>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">Terms of Employment: Fulltime and permanent</span></span></p>\n<p>\n\t&nbsp;</p>\n<p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt">\n\t<span id="docs-internal-guid-8f50239e-7fff-4202-a1a8-522847d6f282"><span style="font-size: 12pt;, serif;background-color: transparent;vertical-align: baseline">Benefits: 4 % Vacation Pay, dental plan, health care plan, pension plan and other benefits.</span></span></p>\n<div>\n\t&nbsp;</div>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf30",
    jobTitle: "Office Administrator",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "JM BUILT HOMES LTD.",
    addressLocality: "Wetaskiwin",
    addressRegion: "AB",
    language: "English",
    minCompValue: "30.00",
    compTimeUnit: "HOUR",
    email: "jmbuilthomes@gmail.com",
    jobPageId: "office-administrator-620",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Location</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span><span>133 Cypress Dr&nbsp;</span><span>Wetaskiwin</span>,&nbsp;<span>AB&nbsp;</span><span class="nomargin">T9A 1K6</span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Salary</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value"><span><span>30.00</span>&nbsp;hourly</span>&nbsp;/&nbsp;<span>40 hours per Week</span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Terms of employment</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Permanent employment,&nbsp;<span class="attribute-value">Full time</span></span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Day, Evening, Morning</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Start date</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>Starts as soon as possible</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">vacancies</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>1 vacancy</span></p>\n<h3 style="font-family: Roboto, Helvetica, Arial, sans-serif;line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\tOverview</h3>\n<div class="comparisonchart" id="comparisonchart" style="font-family: Roboto, Helvetica, Arial, sans-serif;font-size: 15px">\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tLanguages</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\tEnglish</p>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tEducation</h4>\n<ul class="csvlist " style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t<span>Secondary (high) school graduation certificate</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tExperience</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\t<span>1 year to less than 2 years</span></p>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tResponsibilities</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tTasks</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Review and evaluate new administrative procedures</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Establish work priorities and ensure procedures are followed and deadlines are met</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Carry out administrative activities of establishment</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Co-ordinate and plan for office services such as accommodation, relocation, equipment, supplies, forms, disposal of assets, parking, maintenance and security services</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Assist in the preparation of operating budget and maintain inventory and budgetary controls</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Assemble data and prepare periodic and special reports, manuals and correspondence</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Oversee and co-ordinate office administrative procedures</span></li>\n</ul></div>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tAdditional information</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tWork conditions and physical capabilities</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Ability to work independently</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Attention to detail</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tPersonal suitability</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Flexibility</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Organized</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Reliability</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Team player</span></li>\n</ul></div>\n</div>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c744465d3cca810bf32",
    jobTitle: "Production Helper NOC 95106",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Indianlife Food Corporation",
    addressLocality: "Burnaby",
    addressRegion: "BC",
    language: "English",
    minCompValue: "18.00",
    email: "indianlifefoodcorporation@outlook.com",
    jobPageId: "production-helper-noc-95106",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tIndianlife Food Corporation located at 3835 2<sup>nd</sup> Ave, Burnaby, British Columbia, V5C 3W7 is looking for the position of Full Time Permanent 01 Production Helper NOC 95106 to join them.</p>\n<p>\n\tPosition: 01(Full-time)<br>\n\tWage: $18.00/hour<br>\n\tLanguage: English</p>\n<p>\n\tWork Setting: Relocation Costs covered by employer.<br>\n\t&nbsp;</p>\n<p>\n\tJob Duties:</p>\n<ul>\n<li>\n\t\tProvide Customer Services</li>\n<li>\n\t\tManually pack goods in to bags and boxes or other containers</li>\n<li>\n\t\tCheck products and packaging for basic quality defects.</li>\n<li>\n\t\tClean machines and immediate work areas</li>\n</ul>\n<p style="margin-left:.5in">\n\t&nbsp;</p>\n<p>\n\tEducation &amp; Experience:<br>\n\t• No specific education is required.<br>\n\t• Experience is an asset.</p>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf34",
    jobTitle: "Office Administrator",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "JM BUILT HOMES LTD.",
    addressLocality: "Wetaskiwin",
    addressRegion: "AB",
    language: "English",
    minCompValue: "30.00",
    compTimeUnit: "HOUR",
    email: "jmbuilthomes@gmail.com",
    jobPageId: "office-administrator-619",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span><span>133 Cypress Dr&nbsp;</span><span>Wetaskiwin</span>,&nbsp;<span>AB&nbsp;</span><span class="nomargin">T9A 1K6</span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Salary</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value"><span><span>30.00</span>&nbsp;hourly</span>&nbsp;/&nbsp;<span>40 hours per Week</span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Terms of employment</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Permanent employment,&nbsp;<span class="attribute-value">Full time</span></span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Day, Evening, Morning</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Start date</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>Starts as soon as possible</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">vacancies</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>1 vacancy</span></p>\n<h3 style="font-family: Roboto, Helvetica, Arial, sans-serif;line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\tOverview</h3>\n<div class="comparisonchart" id="comparisonchart" style="font-family: Roboto, Helvetica, Arial, sans-serif;font-size: 15px">\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tLanguages</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\tEnglish</p>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tEducation</h4>\n<ul class="csvlist " style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t<span>Secondary (high) school graduation certificate</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tExperience</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\t<span>1 year to less than 2 years</span></p>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tResponsibilities</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tTasks</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Review and evaluate new administrative procedures</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Establish work priorities and ensure procedures are followed and deadlines are met</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Carry out administrative activities of establishment</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Co-ordinate and plan for office services such as accommodation, relocation, equipment, supplies, forms, disposal of assets, parking, maintenance and security services</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Assist in the preparation of operating budget and maintain inventory and budgetary controls</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Assemble data and prepare periodic and special reports, manuals and correspondence</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Oversee and co-ordinate office administrative procedures</span></li>\n</ul></div>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tAdditional information</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tWork conditions and physical capabilities</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Ability to work independently</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Attention to detail</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tPersonal suitability</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Flexibility</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Organized</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Reliability</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Team player</span></li>\n</ul></div>\n</div>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf36",
    jobTitle: "Construction Painters Supervisor",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Chacha G Construction Ltd.",
    addressLocality: "Kelowna",
    addressRegion: "BC",
    language: "English",
    minCompValue: "36.00",
    compTimeUnit: "HOUR",
    email: "chachagconstructionltd@gmail.com",
    jobPageId: "construction-painters-supervisor-8",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tChacha G Construction Ltd. is looking for 2 full-time and permanent Construction Painter Supervisor at 963 Duggan Ct, Kelowna, BC, V1X 7C8. (Even though this is full-time position we encourage part time job seekers to apply as well). Salary is 36.00/hr and 35-40 hours/week.</p>\n<p>\n\tDuties:</p>\n<ul>\n<li>\n\t\tOversee workers and projects</li>\n<li>\n\t\tPlan and organize tasks</li>\n<li>\n\t\tHire workers and manage staffing needs</li>\n<li>\n\t\tArrange training for workers</li>\n<li>\n\t\tInstall machines and equipment</li>\n<li>\n\t\tCalculate costs and materials</li>\n<li>\n\t\tEnsure health and safety rules are followed</li>\n<li>\n\t\tRead blueprints and plans</li>\n<li>\n\t\tOrder materials, equipment, and supplies</li>\n<li>\n\t\tGuide and instruct people</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\tEmployment Requirements:</p>\n<p>\n\tSeveral years of related experience are usually required, or Previous supervisory experience is required</p>\n<p>\n\tHow to apply:</p>\n<p>\n\tPlease email at&nbsp;<a href="mailto:chachagconstructionltd@gmail.com">chachagconstructionltd@gmail.com</a></p>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf38",
    jobTitle: "Bookkeeper",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Excel Training Academy Ontario Inc.",
    addressLocality: "Mississauga",
    addressRegion: "ON",
    language: "English",
    minCompValue: "28.85",
    compTimeUnit: "HOUR",
    email: "jobs.exceltrainingacademy@gmail.com",
    jobPageId: "bookkeeper-941",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<div>\n\tExcel Training Academy Ontario Inc. is looking for 2 full-time and permanent Bookkeeper at 1180 Midway Blvd suite Unit 4 Mississauga, ON L5T 2B9. (Even though this is full-time position we encourage part time job seekers to apply as well). Salary is 28.85/hr and 35 hours/week.</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tDuties:</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tKeep financial records and establish, maintain and balance various accounts using manual and computerized bookkeeping systems</div>\n<div>\n\tPost journal entries and reconcile accounts, prepare trial balance of books, maintain general ledgers and prepare financial statements</div>\n<div>\n\tCalculate and prepare cheques for payrolls and for utility, tax and other bills</div>\n<div>\n\tComplete and submit tax remittance forms, workers' compensation forms, pension contribution forms and other government documents</div>\n<div>\n\tPrepare tax returns and perform other personal bookkeeping services</div>\n<div>\n\tPrepare other statistical, financial and accounting reports.</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tEmployment Requirements:</div>\n<div>\n\tCompletion of secondary school is required/ Completion of a college program in accounting, bookkeeping or a related field or Completion of two years of a recognized professional accounting program or Courses in accounting or bookkeeping combined with several years of experience as a financial or accounting clerk is required.</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tHow to apply:</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tPlease email at jobs.exceltrainingacademy@gmail.com</div>\n<div>\n\t&nbsp;</div>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf3a",
    jobTitle: "Construction Labourer",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "JM BUILT HOMES LTD.",
    addressLocality: "Wetaskiwin",
    addressRegion: "AB",
    language: "English",
    minCompValue: "29.50",
    compTimeUnit: "HOUR",
    email: "jmbuilthomes@gmail.com",
    jobPageId: "construction-labourer-90",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span><span>133 Cypress Dr&nbsp;</span><span>Wetaskiwin</span>,&nbsp;<span>AB&nbsp;</span><span class="nomargin">T9A 1K6</span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Salary</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value"><span><span>29.50</span>&nbsp;hourly</span>&nbsp;/&nbsp;<span>40 hours per Week</span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Terms of employment</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Permanent employment,&nbsp;<span class="attribute-value">Full time</span></span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Day, Evening, Morning</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Start date</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>Starts as soon as possible</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">vacancies</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>1 vacancy</span></p>\n<h3 style="font-family: Roboto, Helvetica, Arial, sans-serif;line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\tOverview</h3>\n<div class="comparisonchart" id="comparisonchart" style="font-family: Roboto, Helvetica, Arial, sans-serif;font-size: 15px">\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tLanguages</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\tEnglish</p>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tEducation</h4>\n<ul class="csvlist " style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t<span>No degree, certificate or diploma</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tExperience</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\t<span>1 to less than 7 months</span></p>\n<div>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tWork site environment</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Outdoors</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>At heights</span></li>\n</ul></div>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tResponsibilities</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tTasks</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Load, unload and transport construction materials</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Mix, pour and spread materials such as concrete and asphalt</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Assist in aligning pipes during pipeline construction</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Assist in framing houses, erecting walls and building roofs</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Clean up chemical spills and other contaminants</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Direct traffic at or near construction sites</span></li>\n</ul></div>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tAdditional information</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tTransportation/travel information</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Willing to travel regularly</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tWork conditions and physical capabilities</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Repetitive tasks</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tPersonal suitability</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Dependability</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Flexibility</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Reliability</span></li>\n</ul></div>\n</div>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf3c",
    jobTitle: "Administrative Assistant",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Excel Training Academy Ontario Inc.",
    addressLocality: "Mississauga",
    addressRegion: "ON",
    language: "English",
    minCompValue: "28.85",
    compTimeUnit: "HOUR",
    email: "jobs.exceltrainingacademy@gmail.com",
    jobPageId: "administrative-assistant-1261",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<div>\n\tExcel Training Academy Ontario Inc. is looking for a full-time and permanent 2 Administrative Assistant at 1180 Midway Blvd suite Unit 4 Mississauga, ON L5T 2B9. (Even though this is full-time position we encourage part time job seekers to apply as well). Salary is 28.85/hr and 35-40 hours/week.</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tJob Description:</div>\n<div>\n\tPrepare, key in, edit and proofread correspondence, invoices etc.</div>\n<div>\n\tOpen and distribute incoming regular and electronic mail and other material and co-ordinate the flow of information internally.</div>\n<div>\n\tSchedule and confirm appointments and meetings of employer.</div>\n<div>\n\tOrder office supplies and maintain inventory.</div>\n<div>\n\tAnswer telephone and electronic enquiries; relay telephone calls and messages.</div>\n<div>\n\tSet up and maintain manual and computerized information filing systems.</div>\n<div>\n\tDetermine and establish office procedures.</div>\n<div>\n\tGreet people and direct them to contacts or service areas.</div>\n<div>\n\tRecord and prepare minutes of meetings.</div>\n<div>\n\tArrange travel schedules, related itineraries and make reservations.</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tEmployment Requirements: Secondary (high) school graduation certificate is required. Completion of a one- or two-year college or other program for administrative assistants or secretaries or previous 1-7 months clerical experience is required.</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tHow to apply:</div>\n<div>\n\t&nbsp;</div>\n<div>\n\tPlease email resume at jobs.exceltrainingacademy@gmail.com</div>\n<div>\n\t&nbsp;</div>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf3e",
    jobTitle: "Administrative Assistant",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "1447036 B.C LTD.",
    addressLocality: "Vancouver",
    addressRegion: "BC",
    language: "English",
    minCompValue: "25.00",
    email: "emailrecruitment.general.apply.now@gmail.com",
    jobPageId: "administrative-assistant-1260",
    employmentSubType: "Full Time",
    validThrough: "2024-11-23T08:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit;">Overview</strong></p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit;">Languages</strong>&nbsp;:English</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit;">Education:</strong>&nbsp;Secondary (high) school graduation certificate</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit;">Experience:&nbsp;</strong>1&nbsp;year to less than 2 years</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit;">Responsibilities</strong></p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit;">Tasks</strong></p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Coordinate the flow of information within the team</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Open and distribute mail and other materials</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Record and prepare minutes of meetings, seminars and conferences</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Determine and establish office procedures and routines</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Schedule and confirm appointments</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Answer telephone and relay telephone calls and messages</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Answer electronic enquiries</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Compile data, statistics and other information</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Order office supplies and maintain inventory Arrange travel, related itineraries and make reservations</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Greet people and direct them to contacts or service areas</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Set up and maintain manual and computerized information filing systems</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Type and proofread correspondence, forms and other documents</p>\n<p style="margin: 0px 0px 10px; padding: 0px 0px 0px 35px; border: 0px; font-style: italic; font-size: 14px; line-height: 20px; font-family: Roboto, sans-serif;">Supervise office and volunteer staff</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf40",
    jobTitle: "Retail Store Supervisor",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Compassion Pharmacy",
    addressLocality: "Edmonton",
    addressRegion: "AB",
    language: "English",
    minCompValue: "29.50",
    compTimeUnit: "HOUR",
    email: "compassionpharma.jobs@gmail.com",
    jobPageId: "retail-store-supervisor-943",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span><span class="city"><span>Edmonton</span>,&nbsp;<span>AB&nbsp;</span><span class="nomargin">T6W 4S1</span></span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Salary</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value"><span><span>29.50</span>&nbsp;hourly</span>&nbsp;/&nbsp;<span>40 hours per Week</span></span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Terms of employment</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Permanent employment,&nbsp;<span class="attribute-value">Full time</span></span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span class="attribute-value">Day, Evening, Morning</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">Start date</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>Starts as soon as possible</span></p>\n<p>\n\t<span class="wb-inv" style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important;height: 1px;margin: 0px;overflow: hidden;position: absolute;width: 1px">vacancies</span></p>\n<p style="margin: 0px 0px 12px;line-height: 19px;border: 0px;padding-left: 25px;min-width: 200px !important">\n\t<span>2 vacancies</span></p>\n<h3 style="font-family: Roboto, Helvetica, Arial, sans-serif;line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\tOverview</h3>\n<div class="comparisonchart" id="comparisonchart" style="font-family: Roboto, Helvetica, Arial, sans-serif;font-size: 15px">\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tLanguages</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\tEnglish</p>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tEducation</h4>\n<ul class="csvlist " style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t<span>Secondary (high) school graduation certificate</span></li>\n</ul>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\tExperience</h4>\n<p style="margin: 0px 0px 0px 20px;line-height: 21px">\n\t\t<span>1 year to less than 2 years</span></p>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tResponsibilities</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tTasks</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Order merchandise</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Authorize return of merchandise</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Establish work schedules</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Sell merchandise</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Prepare reports on sales volumes, merchandising and personnel matters</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Resolve issues that may arise, including customer requests, complaints and supply shortages</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Organize and maintain inventory</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Supervise and co-ordinate activities of workers</span></li>\n</ul></div>\n<div>\n<h3 style="line-height: 1.1;margin: 30px 0px 0px;font-size: 20px">\n\t\t\tAdditional information</h3>\n<h4 style="font-weight: 500;line-height: 1.1;margin: 20px 0px 8px;font-size: 16px">\n\t\t\tPersonal suitability</h4>\n<ul class="csvlist" style="margin: 5px 0px;padding-right: 0px;padding-left: 0px;list-style-type: none">\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Flexibility</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Organized</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Reliability</span></li>\n<li style="line-height: normal;margin: 0px 0px 5px 20px">\n\t\t\t\t<span>Initiative</span></li>\n</ul></div>\n</div>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf42",
    jobTitle: "Office Administrative Assistant",
    datePosted: "2024-05-27T07:00:00.000Z",
    hiringOrganization: "Tung & Sidhu Ltd. O/A Pizza Hut",
    addressLocality: "Sidney",
    addressRegion: "BC",
    language: "English",
    minCompValue: "24.95",
    compTimeUnit: "HOUR",
    email: "sidneypizzahut@hotmail.com",
    jobPageId: "office-administrative-assistant-311",
    employmentSubType: "Full Time",
    validThrough: "2025-05-27T07:00:00.000Z",
    description:
      "\n\n\n\n\n\n\n\n\n\n\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tTung &amp; Sidhu Ltd. O/A Pizza Hut is looking for a full-time and permanent 1 Administrative Assistant at 203 – 9810 7th Street Sidney, BC V8L 4W6. (Even though this is full-time position we encourage part time job seekers to apply as well). Salary is 24.95/hr and 35-40 hours/week.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tJob Description:</p>\n<p>\n\tPrepare, key in, edit and proofread correspondence, invoices etc.</p>\n<p>\n\tOpen and distribute incoming regular and electronic mail and other material and co-ordinate the flow of information internally.</p>\n<p>\n\tSchedule and confirm appointments and meetings of employer.</p>\n<p>\n\tOrder office supplies and maintain inventory.</p>\n<p>\n\tAnswer telephone and electronic enquiries; relay telephone calls and messages.</p>\n<p>\n\tSet up and maintain manual and computerized information filing systems.</p>\n<p>\n\tDetermine and establish office procedures.</p>\n<p>\n\tGreet people and direct them to contacts or service areas.</p>\n<p>\n\tRecord and prepare minutes of meetings.</p>\n<p>\n\tArrange travel schedules, related itineraries and make reservations.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tEmployment Requirements: Secondary (high) school graduation certificate is required. Completion of a one- or two-year college or other program for administrative assistants or secretaries or previous 1-7 months clerical experience is required.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tHow to apply:</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tPlease email resume at sidneypizzahut@hotmail.com</p>\n<p>\n\t&nbsp;</p>\n",
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf44",
    jobTitle: "Landscaper",
    datePosted: "2024-05-22T07:00:00.000Z",
    hiringOrganization: "Maplewood Landscaping Ltd.",
    addressLocality: "Maple Ridge",
    addressRegion: "BC",
    language: "English",
    minCompValue: "24.00",
    compTimeUnit: "HOUR",
    email: "maplewood-hiring@outlook.com",
    jobPageId: "landscaper-15",
    employmentSubType: "Full Time",
    validThrough: "2025-05-22T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n<img width="103" height="68" src="https://www.newcomersjobcentre.ca/wp-content/uploads/company_logos/2024/05/maplewood-landscapes-logo.png" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" decoding="async" original="https://www.newcomersjobcentre.ca/wp-content/uploads/company_logos/2024/05/maplewood-landscapes-logo.png">\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tAre you passionate about landscaping? Do you thrive in a collaborative team environment, tackling new challenges with dedication and skill? Look no further! Maplewood Landscaping Ltd. is seeking talented individuals to join our esteemed team of professionals.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tJoin Our Elite Team at Maplewood Landscaping Ltd., located at 3520 40th Street, Delta BC V4K 3N2, Canada.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tWhy join Maplewood Landscaping Ltd:</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tExceptional Service: Our team is committed to providing nothing but the best for our clients.</p>\n<p>\n\tQuality Assurance: We never compromise on materials or craftsmanship, ensuring lasting results.</p>\n<p>\n\tTeam Spirit: Work alongside passionate individuals who support each other in delivering excellence.</p>\n<p>\n\tThriving Environment: Embrace new challenges and opportunities for growth in a dynamic workplace.</p>\n<p>\n\tCustomer Satisfaction: Help us exceed expectations and leave a lasting impression on our valued customers.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tIf you\'re ready to embark on a rewarding career in landscaping and meet our requirements, we want to hear from you! Join Maplewood Landscaping Ltd. and become an integral part of our success story.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\tDon\'t miss this chance to elevate your career with Maplewood Landscaping Ltd.! Apply now and let your skills blossom with us.</p>\n<p>\n\t<strong>Job Description:</strong></p>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong>Position</strong>: Landscaper</p>\n<p>\n\t<strong>Positions available</strong>: 1</p>\n<p>\n\t<strong>Work Hours</strong>:&nbsp; 40 hours per week</p>\n<p>\n\t<strong>Wage</strong>:&nbsp;$24.00/hour</p>\n<p>\n\t<strong>Language of work:&nbsp;</strong>English</p>\n<p>\n\t<strong>Employment Type</strong>:&nbsp;Full-time, Permanent</p>\n<p>\n\t<strong>Start date</strong>: ASAP</p>\n<p>\n\t<strong>Work Location</strong>: 3520 40th Street, Delta BC V4K 3N2, Canada</p>\n<p>\n\t<strong>Language of work:&nbsp;</strong>English</p>\n<p>\n\t<strong>Job benefits:</strong>&nbsp;As per law</p>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong>Key duties and responsibilities:</strong></p>\n<p>\n\t&nbsp;</p>\n<ul>\n<li>\n\t\tAssisting with various types of installations including, but not limited to excavation, drainage, paving stones (concrete and stone), retaining walls (concrete and stone), poured concrete prep, natural &amp; artificial grass, soil, planting.</li>\n<li>\n\t\tPlan and co-ordinate the growth and use of plants for landscaping, ornamental uses, and other purposes.</li>\n<li>\n\t\tWater and tend to plants, lawns and/or gardens.</li>\n<li>\n\t\tPlant and maintain private and public lawns and gardens.</li>\n<li>\n\t\tGarden &amp; lawn maintenance for commercial, residential, and strata clients.</li>\n<li>\n\t\tApply fertilizers, fungicides, herbicides, pesticides, and other lawn care products.</li>\n<li>\n\t\tApply various treatments such as pruning, spraying, repairing damaged areas and injecting with treatment solutions.</li>\n<li>\n\t\tExamine trees and shrubs to diagnose problems and disease</li>\n<li>\n\t\tPlant and move trees.</li>\n<li>\n\t\tClean snow and ice from walkways and parking areas.</li>\n</ul>\n<p style="margin-left: 35.45pt">\n\t&nbsp;</p>\n<p>\n\t<strong>Requirements for the job:</strong></p>\n<p>\n\t&nbsp;</p>\n<ul>\n<li>\n\t\tCompletion of secondary school.</li>\n<li>\n\t\tPrevious work experience in the same or a related job position is an asset.</li>\n<li>\n\t\tPhysical demanding: bending crouching and kneeling, ability to lift up to 23 kg</li>\n<li>\n\t\tAttention to detail.</li>\n<li>\n\t\tAbility to work independently.</li>\n<li>\n\t\tRepetitive tasks.</li>\n<li>\n\t\tHandling heavy loads.</li>\n<li>\n\t\tPhysically demanding.</li>\n<li>\n\t\tManual dexterity.</li>\n<li>\n\t\tCombination of sitting, standing, walking.</li>\n<li>\n\t\tStanding for extended periods.</li>\n</ul>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c754465d3cca810bf46",
    jobTitle: "Sales Supervisor",
    datePosted: "2024-05-21T07:00:00.000Z",
    hiringOrganization: "Applebarn Pumpkin Farm Ltd.",
    addressLocality: "Abbotsford",
    addressRegion: "BC",
    language: "English",
    minCompValue: "22.95",
    compTimeUnit: "HOUR",
    email: "tavesfamilyfarmsapplebarn@gmail.com",
    jobPageId: "sales-supervisor-78",
    employmentSubType: "Full Time",
    validThrough: "2024-11-17T08:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n<img width="213" height="195" src="https://www.newcomersjobcentre.ca/wp-content/uploads/company_logos/2024/05/applebarn-logo.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" decoding="async" original="https://www.newcomersjobcentre.ca/wp-content/uploads/company_logos/2024/05/applebarn-logo.jpg">\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tWe will be the first ones to tell you that living on a farm in the Fraser Valley is living the dream. One farm quickly grew to a few, and now we harvest everything from apples to heirloom tomatoes to pumpkins. Every August, we open the doors to U-pick to our communities so they can pick their own apples or bring their families out for some fall family entertainment!</p>\n<p>\n\t&nbsp;</p>\n<p>\n\t&nbsp;We are looking for a persistent, detail oriented, systematic, careful, and energetic person to join our team as part of our Sales team. The ideal candidate is a team player, keen to learn, self-motivator and able to work well under pressure and take pride in their&nbsp;work. The candidate must be a quick learner, great&nbsp;at multitasking, with excellent sales skills and oversee sales activities.</p>\n<p>\n\t&nbsp;</p>\n<p>\n\t&nbsp;</p>\n<ul>\n<li>\n\t\t<strong>Employer:</strong>&nbsp; Applebarn Pumpkin Farm Ltd.</li>\n<li>\n\t\t<strong>Position: </strong>&nbsp;Sales Supervisor</li>\n<li>\n\t\t<strong>Terms of Employment: </strong>Full-time / Permanent</li>\n<li>\n\t\t<strong>Location:</strong> 333 Gladwin Rd, Abbotsford, British Columbia V2T 5Y1</li>\n<li>\n\t\t<strong>Employment Address: </strong>333 Gladwin Rd, Abbotsford, British Columbia V2T 5Y1</li>\n<li>\n\t\t<strong>Hours of Work: </strong>30 hours/week</li>\n<li>\n\t\t<strong>Language: </strong>English</li>\n<li>\n\t\t<strong>Salar</strong><strong>y: </strong>$22.95 / hour</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong><u>Key duties and Responsibilities</u></strong></p>\n<ul>\n<li>\n\t\tUnderstand customer needs and offer solutions and support properly</li>\n<li>\n\t\tOrganize and coordinate sales representatives schedules</li>\n<li>\n\t\tResearch potential leads from business directories, web searches, or digital resources</li>\n<li>\n\t\tRecruit, hire, and train new sales representatives</li>\n<li>\n\t\tTrack weekly, monthly, and quarterly performance and sales metrics</li>\n<li>\n\t\tReport on all sales activities to the director</li>\n<li>\n\t\tSupervise sales representatives and assistants</li>\n<li>\n\t\tAnswer potential customer questions and follow-up call questions</li>\n<li>\n\t\tLead the sales team</li>\n<li>\n\t\tMeet all sales quotas and goals</li>\n<li>\n\t\tAssist sales representatives and team to meet and exceed goals</li>\n<li>\n\t\tResolve issues about customer requests, complaints and supply shortages</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong><u>Requirements/Education and other requirements</u></strong></p>\n<ul>\n<li>\n\t\tCompletion of secondary school is required</li>\n<li>\n\t\tPrevious retail sales experience as a retail salesperson or sales clerk, cashier is required</li>\n<li>\n\t\tExcellent written and verbal communications skills is a requirement, while the ability to communicate in languages other than English is an asset</li>\n<li>\n\t\tTeam player who is keen to learn and develop themselves while working in a team</li>\n<li>\n\t\tQuick learner and excellent multi-tasker</li>\n<li>\n\t\tPersistent, detail-oriented, systematic, careful, and energetic</li>\n</ul>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c764465d3cca810bf48",
    jobTitle: "Office Administrator",
    datePosted: "2024-05-20T07:00:00.000Z",
    hiringOrganization: "Spade Transport Ltd.",
    addressLocality: "Steinbach",
    addressRegion: "MB",
    language: "English",
    minCompValue: "25.20",
    compTimeUnit: "HOUR",
    email: "arshdeepbishnandi@outlook.com",
    jobPageId: "administrative-assistant-1254",
    employmentSubType: "Full Time",
    validThrough: "2025-05-20T07:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n<img width="250" height="250" src="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-250x250.png.webp" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" decoding="async" fetchpriority="high" srcset="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-250x250.png.webp 250w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-300x300.png.webp 300w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-1024x1024.png.webp 1024w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-150x150.png.webp 150w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-768x768.png.webp 768w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-48x48.png.webp 48w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-28x28.png.webp 28w, https://www.newcomersjobcentre.ca/wp-content/uploads/company_logos/2024/05/Logo-NB.png 1200w" sizes="(max-width: 250px) 100vw, 250px" original="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Logo-NB-250x250.png.webp">\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tLanguages: English</p>\n<p>\n\tEducation: Secondary (high) school graduation certificate</p>\n<p>\n\tExperience: 1 year to less than 2 years</p>\n<p>\n\tResponsibilities:</p>\n<ul>\n<li>\n\t\tReview and evaluate new administrative procedures</li>\n<li>\n\t\tDelegate work to office support staff</li>\n<li>\n\t\tEstablish work priorities and ensure procedures are followed and deadlines are met</li>\n<li>\n\t\tCarry out administrative activities of establishment</li>\n<li>\n\t\tAdminister policies and procedures related to the release of records in processing requests under government access to information and privacy legislation</li>\n<li>\n\t\tAssemble data and prepare periodic and special reports, manuals and correspondence</li>\n<li>\n\t\tPerform data entry</li>\n<li>\n\t\tOversee and co-ordinate office administrative procedures</li>\n<li>\n\t\tOversee payroll administration</li>\n</ul>\n<p>\n\tSupervision: 1 to 2 people</p>\n<p>\n\tComputer and technology knowledge</p>\n<ul>\n<li>\n\t\tElectronic mail</li>\n<li>\n\t\tMS Windows</li>\n<li>\n\t\tMS Word</li>\n</ul>\n<p>\n\tWork conditions and physical capabilities</p>\n<ul>\n<li>\n\t\tFast-paced environment</li>\n<li>\n\t\tWork under pressure</li>\n</ul>\n<p>\n\tPersonal suitability</p>\n<ul>\n<li>\n\t\tEfficient interpersonal skills</li>\n<li>\n\t\tExcellent oral communication</li>\n<li>\n\t\tExcellent written communication</li>\n<li>\n\t\tOrganized</li>\n<li>\n\t\tReliability</li>\n</ul>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c764465d3cca810bf4a",
    jobTitle: "Painter",
    datePosted: "2024-05-15T07:00:00.000Z",
    hiringOrganization: "Warline Painting Ltd.",
    addressLocality: "Surrey",
    addressRegion: "BC",
    language: "English",
    minCompValue: "26.00",
    compTimeUnit: "HOUR",
    email: "jobs@warline.ca",
    jobPageId: "painter-135",
    employmentSubType: "Full Time",
    validThrough: "2024-11-11T08:00:00.000Z",
    description:
      '\n\n\n\n\n\n\n\n\n\n<img width="250" height="46" src="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Warline-logo-250x46.png.webp" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" decoding="async" srcset="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Warline-logo-250x46.png.webp 250w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Warline-logo-300x55.png.webp 300w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Warline-logo-1024x188.png.webp 1024w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Warline-logo-768x141.png.webp 768w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Warline-logo-1536x282.png.webp 1536w, https://www.newcomersjobcentre.ca/wp-content/uploads/company_logos/2024/05/Warline-logo.png 2048w" sizes="(max-width: 250px) 100vw, 250px" original="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2024/05/Warline-logo-250x46.png.webp">\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<p>\n\tWarline Painting is a quality first, premier painting company in Vancouver that specializes in the interior and exterior painting of residences, commercial buildings, strata complexes and new construction projects throughout the greater Vancouver area. We provide exceptional customer service, quality workmanship and use best practices in all our work and projects.</p>\n<p>\n\tWe offer pay for performance, training, and extended health care for full-time employees.</p>\n<ul>\n<li>\n\t\t<strong>Vacancies: </strong>1</li>\n<li>\n\t\t<strong>Position</strong>: Painter</li>\n<li>\n\t\t<strong>Work Hours</strong>: 40 hours/week</li>\n<li>\n\t\t<strong>Wage</strong>:&nbsp;$26/h</li>\n<li>\n\t\t<strong>Job Type</strong>:&nbsp;Full-time, Permanent</li>\n<li>\n\t\t<strong>Start date</strong>: ASAP</li>\n<li>\n\t\t<strong>Benefits</strong>: extended health care</li>\n<li>\n\t\t<strong>Address</strong>: 111 – 18635 52nd Avenue, Surrey BC V3S 8E5</li>\n</ul>\n<p>\n\t&nbsp;</p>\n<p>\n\t<strong>Key duties and Responsibilities</strong></p>\n<ul>\n<li>\n\t\tAdhering to Warline\'s rules of conduct and safety at all times</li>\n<li>\n\t\tConducting yourself in a professional and courteous manner with our customers</li>\n<li>\n\t\tShow a willingness to learn and ability to lead and provide direction</li>\n<li>\n\t\tWork in a team environment as well as have ability to work independently</li>\n<li>\n\t\tWork safely with ladders, lift equipment and use of personal fall protection</li>\n<li>\n\t\tRead and follow a scope of work and colour schedule</li>\n<li>\n\t\tPlan sequencing of job and materials required</li>\n<li>\n\t\tPrep and painting of surfaces as required</li>\n<li>\n\t\tMaintaining a clean workplace</li>\n<li>\n\t\tDaily set up and clean up</li>\n<li>\n\t\tRecord hours and description of work on time sheets of daily activities</li>\n<li>\n\t\tArrive to work on time daily, ready to work at start time</li>\n<li>\n\t\tAdhere to our strict non-smoking policy</li>\n</ul>\n<p style="margin-left:36.0pt">\n\t&nbsp;</p>\n<p>\n\t<strong>Requirements/Education and other requirements</strong></p>\n<ul>\n<li>\n\t\tCompletion of secondary school</li>\n<li>\n\t\t2 – 3 years experience in interior and exterior painting</li>\n<li>\n\t\tHave the tools of the profession</li>\n<li>\n\t\tA strong work ethic</li>\n<li>\n\t\tHave a neat and tidy, professional appearance</li>\n<li>\n\t\tAn eye for detail and desire to work to best practices</li>\n<li>\n\t\tHave strong English skills, both written and verbal</li>\n<li>\n\t\tThe ability to work efficiently, cleanly and safely</li>\n<li>\n\t\tA vehicle to get to multiple job sites through-out the Greater Vancouver area</li>\n<li>\n\t\tA keen interest in advancing your career in the painting industry</li>\n</ul>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
  {
    _id: "66569c764465d3cca810bf4c",
    jobTitle: "Irrigation Technician at Kore Ventures Inc.",
    datePosted: "2024-05-15T07:00:00.000Z",
    hiringOrganization: "Kore Ventures Inc.",
    addressLocality: "Surrey",
    addressRegion: "BC",
    language: "English",
    minCompValue: "26.92",
    compTimeUnit: "HOUR",
    email: "apply.koreventures@gmail.com",
    jobPageId: "irrigation-technician-at-kore-ventures-inc-2",
    employmentSubType: "Full Time",
    validThrough: "1970-01-01T08:00:00.000Z",
    description:
      '\n\n\n\n<p class="expired"><strong>NOTE:</strong> This job listing has expired and may no longer be relevant!</p>\n\n\n\n\n\n<img width="250" height="88" src="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2023/04/Kore-Ventures-logo-250x88.png.webp" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" decoding="async" srcset="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2023/04/Kore-Ventures-logo-250x88.png.webp 250w, https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2023/04/Kore-Ventures-logo-300x106.png.webp 300w, https://www.newcomersjobcentre.ca/wp-content/uploads/company_logos/2023/04/Kore-Ventures-logo.png 375w" sizes="(max-width: 250px) 100vw, 250px" original="https://www.newcomersjobcentre.ca/wp-content/smush-webp/company_logos/2023/04/Kore-Ventures-logo-250x88.png.webp">\n\n\n<h2>Description</h2>\n\n\n\n\n\n\n<table border="0" cellpadding="0" cellspacing="0">\n<tbody>\n<tr>\n<td>\n<p>\n\t\t\t\t\t<strong>Irrigation Technician (NOC 73200) </strong></p>\n<p>\n\t\t\t\t\t&nbsp;</p>\n<p>\n\t\t\t\t\tKore Ventures Inc. services the entire Vancouver Lower Mainland, from Squamish to Chilliwack offering irrigation and landscape lighting services. Our specialists can design a lawn irrigation system or an outdoor landscape lighting system for residential or commercial properties.</p>\n<p>\n\t\t\t\t\tWe are currently looking for an Irrigation Technician to join our team on our many projects across the Lower Mainland.</p>\n<ul>\n<li>\n\t\t\t\t\t\tPosition: Irrigation Technician</li>\n<li>\n\t\t\t\t\t\tWork Hours:&nbsp; 40 hrs. per week</li>\n<li>\n\t\t\t\t\t\tWage:&nbsp;$26.92</li>\n<li>\n\t\t\t\t\t\tJob Type:&nbsp;Full-time, Permanent</li>\n<li>\n\t\t\t\t\t\tStart date: ASAP</li>\n<li>\n\t\t\t\t\t\tBenefits: Dental Insurance, Extended Medical Insurance, 10 business days of vacation</li>\n<li>\n\t\t\t\t\t\tWork Location: reporting to main office located at 110 – 19140 28 Avenue, Surrey, BC, V3Z 6M2.</li>\n</ul>\n<p>\n\t\t\t\t\t&nbsp;</p>\n<p>\n\t\t\t\t\tKey duties and Responsibilities</p>\n<ul>\n<li>\n\t\t\t\t\t\tRead blueprints or work order specifications to determine layout and installation procedures.</li>\n<li>\n\t\t\t\t\t\tMeasure and mark guidelines to be used for installations.</li>\n<li>\n\t\t\t\t\t\tInstall, test, and maintain irrigation equipment including sprinklers, water lines, and suction valves using hand and power tools.</li>\n<li>\n\t\t\t\t\t\tInspecting and loading equipment for the day’s work.</li>\n<li>\n\t\t\t\t\t\tDigging trenches and installing pipes and lines.</li>\n<li>\n\t\t\t\t\t\tInstalling electrical timers.</li>\n<li>\n\t\t\t\t\t\tConducting routine maintenance checks.</li>\n<li>\n\t\t\t\t\t\tTroubleshooting and replacing faulty parts.</li>\n<li>\n\t\t\t\t\t\tCompleting progress reports and associated paperwork.</li>\n</ul>\n<p>\n\t\t\t\t\t&nbsp;</p>\n<p>\n\t\t\t\t\tRequirements/Education and other requirements</p>\n<ul>\n<li>\n\t\t\t\t\t\tSome secondary school education is required.</li>\n<li>\n\t\t\t\t\t\tOn-the-job training and several months of related installing, repairing, or servicing experience are required.</li>\n<li>\n\t\t\t\t\t\tOrganized, self-disciplined, motivated and able to work independently.</li>\n<li>\n\t\t\t\t\t\tInterpersonal communication skills, communicate effectively both written and orally.</li>\n<li>\n\t\t\t\t\t\tA strong work ethic, commitment to team culture, positive attitude.</li>\n</ul>\n<p>\n\t\t\t\t\tInterested candidates should send a cover letter and resume to apply.koreventures@gmail.com</p>\n</td>\n</tr>\n</tbody>\n</table>\n<p>\n\t&nbsp;</p>\n',
    paid: true,
    site1: true,
    site2: true,
    site3: true,
    site4: true,
    site5: true,
    __v: 0,
  },
];

(async function () {
  await Promise.all(
    data.map((jp) =>
      db.insert(jobPostings).values({
        addressLocality: jp.addressLocality,
        addressRegion: jp.addressRegion,
        datePosted: jp.datePosted,
        description: jp.description,
        email: jp.email,
        employmentSubType: jp.employmentSubType,
        hiringOrganization: jp.hiringOrganization,
        jobTitle: jp.jobTitle,
        language: jp.language,
        minCompValue: jp.minCompValue,
        paid: jp.paid,
        validThrough: jp.validThrough,
        compTimeUnit: jp.compTimeUnit,
        jobPageId: jp.jobPageId,
      })
    )
  );
  return "success";
})().catch((err) => console.log(err.message));
