import { db } from "@/db";
import { jobPostings } from "@/db/schema";

const data = [
  {
    jobTitle: "Project Manager",
    organizationName: "Maple Project Management",
    region: "BC",
    city: "Vancouver",
    address: "200 Granville Street",
    startTime: "2025-02-15",
    vacancies: null,
    employmentType: "Full Time",
    workHours: null,
    paymentType: "Salary",
    minPayValue: 85000,
    maxPayValue: null,
    description: "Oversee project timelines and deliverables for our clients.",
    language: "English",
    postAsylum: true,
    postDisabled: true,
    postIndigenous: true,
    postNewcomers: true,
    postYouth: true,
    email: "careers@maplepm.ca",
    createdAt: "2025-01-01T01:00:00Z",
    updatedAt: "2025-01-01T01:00:00Z",
    paymentConfirmed: true,
    expiresAt: "2025-12-31",
  },
  {
    jobTitle: "Software Engineer",
    organizationName: "Northern Tech Solutions",
    region: "ON",
    city: "Toronto",
    address: "100 Bay Street",
    startTime: "2025-01-20",
    vacancies: 5,
    employmentType: "Full Time",
    workHours: 40,
    paymentType: "Salary",
    minPayValue: 40000,
    maxPayValue: 60000,
    description: "Design and develop software applications for our clients.",
    language: null,
    postAsylum: true,
    postDisabled: true,
    postIndigenous: true,
    postNewcomers: true,
    postYouth: true,
    email: "jobs@northerntech.ca",
    createdAt: "2025-01-01T01:00:00Z",
    updatedAt: "2025-01-01T01:00:00Z",
    paymentConfirmed: true,
    expiresAt: "2025-12-31",
  },
  {
    jobTitle: "Customer Support Representative",
    organizationName: "West Coast Call Center",
    region: "AB",
    city: "Calgary",
    address: "400 Centre Street",
    startTime: "2025-02-10",
    vacancies: 10,
    employmentType: "Part Time",
    workHours: 24,
    paymentType: "Hourly",
    minPayValue: 18,
    maxPayValue: null,
    description: "Provide customer support via phone and email.",
    language: "English",
    postAsylum: true,
    postDisabled: true,
    postIndigenous: true,
    postNewcomers: true,
    postYouth: true,
    email: "support@westcoastcall.ca",
    createdAt: "2025-01-01T01:00:00Z",
    updatedAt: "2025-01-01T01:00:00Z",
    paymentConfirmed: true,
    expiresAt: "2025-12-31",
  },
  {
    jobTitle: "Graphic Designer",
    organizationName: "Creative Studios Inc.",
    region: "QC",
    city: "Montreal",
    address: "300 Saint Laurent Blvd",
    startTime: "2025-01-25",
    vacancies: null,
    employmentType: "Part Time",
    workHours: null,
    paymentType: "Hourly",
    minPayValue: 25,
    maxPayValue: 35,
    description: "Create visual designs and graphics for marketing campaigns.",
    language: "French",
    postAsylum: true,
    postDisabled: true,
    postIndigenous: true,
    postNewcomers: true,
    postYouth: true,
    email: "design@creativestudios.ca",
    createdAt: "2025-01-01T01:00:00Z",
    updatedAt: "2025-01-01T01:00:00Z",
    paymentConfirmed: true,
    expiresAt: "2025-12-31",
  },
];

export async function seed() {
  await Promise.all(
    data.map((jp) =>
      db.insert(jobPostings).values({
        jobTitle: jp.jobTitle,
        organizationName: jp.organizationName,
        region: jp.region,
        city: jp.city,
        address: jp.address,
        startTime: jp.startTime,
        vacancies: jp.vacancies,
        employmentType: jp.employmentType,
        workHours: jp.workHours,
        paymentType: jp.paymentType,
        minPayValue: jp.minPayValue,
        maxPayValue: jp.maxPayValue,
        description: jp.description,
        language: jp.language,
        postAsylum: jp.postAsylum,
        postDisabled: jp.postDisabled,
        postIndigenous: jp.postIndigenous,
        postNewcomers: jp.postNewcomers,
        postYouth: jp.postYouth,
        email: jp.email,
        expiresAt: jp.expiresAt,
        paymentConfirmed: jp.paymentConfirmed,
      })
    )
  );
  return "success";
}
