export type JobPosting = {
  id: string;
  email: string;
  jobTitle: string;
  organizationName: string;
  region: string;
  city: string;
  address: string | null;
  startTime: string;
  vacancies: number | null;
  employmentType: string;
  workHours: number | null;
  paymentType: string;
  minPayValue: number;
  maxPayValue: number | null;
  description: string;
  language: string | null;
  postAsylum: boolean;
  postDisabled: boolean;
  postIndigenous: boolean;
  postNewcomers: boolean;
  postYouth: boolean;
  hidden: boolean;
  createdAt: Date;
  updatedAt: Date;
  expiresAt: string;
  paymentConfirmed: boolean;
};
